#!/bin/bash

# Copyright 2014 Curtis L. Knight
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo Cloning branch: $1
git clone --progress git://git.fedorahosted.org/git/freeipa.git --branch $1
cd freeipa
cp -v freeipa.spec.in freeipa-builddep.spec
yum-builddep --enablerepo=updates-testing -y freeipa-builddep.spec
make rpms

if perl -e '( -t ) ? exit 0 : exit 1'; then
	echo 'Starting interactive shell.'
	/bin/bash
else
	echo 'Go loop.'
	while true; do sleep 1000; done
fi
